In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
root =  os.getcwd()
root

'/home/peiretti/fair-clustering'

In [3]:
dataset = "lfw"
sensitive = "gender"

In [4]:
df = pd.read_csv(root + f"/results/{dataset}_{sensitive}.csv")
df

,algorithm,tau_x_mean,tau_x_std,tau_y_mean,tau_y_std,ARI_true_labels_mean,ARI_true_labels_std,ARI_rows_mean,ARI_rows_std,ARI_cols_mean,ARI_cols_std,balance_bera_mean,balance_bera_std,time_mean,time_std
0,taucc_vanilla,0.005400,0.000011,0.005400,0.000011,0.000029,3.026243e-06,NaN,NaN,NaN,NaN,0.939764,0.012641,3.508744,0.835345
1,taucc_fair,0.005390,0.000001,0.005390,0.000001,0.000027,5.939949e-07,0.925566,0.003572,0.938248,0.003281,0.950710,0.001407,28.660028,9.292126
2,taucc_fair_max,0.005364,0.000046,0.005364,0.000046,0.000029,8.068858e-07,0.901993,0.006345,0.932204,0.010360,0.992909,0.000309,25.294427,5.702126
3,lbm_vanilla,0.001955,0.000035,0.001967,0.000070,0.001561,1.840086e-04,NaN,NaN,NaN,NaN,0.393438,0.027894,38414.794401,5950.140080
4,lbm_fair,0.001896,0.000044,0.001908,0.000074,0.001297,8.136348e-05,0.347793,0.030571,0.768439,0.048644,0.803037,0.019489,40201.683551,9781.722494
5,fatr_vanilla,0.000014,0.000036,0.400100,0.210607,0.000895,6.442443e-04,NaN,NaN,NaN,NaN,0.000000,0.000000,8109.904800,39.747839
6,fatr_fair,0.000701,0.000118,0.000568,0.000166,0.000534,4.428914e-04,0.906025,0.115022,0.010154,0.032930,0.227912,0.021209,8109.904800,39.747839

In [5]:
algorithms = {
    "taucc_vanilla": "Fast-$\tau$CC",
    "taucc_fair": "Fair-$\tau$CC v1",
    "taucc_fair_max": "Fair-$\tau$CC v2",
    "lbm_vanilla": "LBM",
    "lbm_fair": "Parity LBM",
    "fatr_vanilla": "FATR vanilla",
    "fatr_fair": "FATR fair"
}

In [6]:
df["algorithm"] = df["algorithm"].replace(algorithms)
df

,algorithm,tau_x_mean,tau_x_std,tau_y_mean,tau_y_std,ARI_true_labels_mean,ARI_true_labels_std,ARI_rows_mean,ARI_rows_std,ARI_cols_mean,ARI_cols_std,balance_bera_mean,balance_bera_std,time_mean,time_std
0,Fast-$\tau$CC,0.005400,0.000011,0.005400,0.000011,0.000029,3.026243e-06,NaN,NaN,NaN,NaN,0.939764,0.012641,3.508744,0.835345
1,Fair-$\tau$CC v1,0.005390,0.000001,0.005390,0.000001,0.000027,5.939949e-07,0.925566,0.003572,0.938248,0.003281,0.950710,0.001407,28.660028,9.292126
2,Fair-$\tau$CC v2,0.005364,0.000046,0.005364,0.000046,0.000029,8.068858e-07,0.901993,0.006345,0.932204,0.010360,0.992909,0.000309,25.294427,5.702126
3,LBM,0.001955,0.000035,0.001967,0.000070,0.001561,1.840086e-04,NaN,NaN,NaN,NaN,0.393438,0.027894,38414.794401,5950.140080
4,Parity LBM,0.001896,0.000044,0.001908,0.000074,0.001297,8.136348e-05,0.347793,0.030571,0.768439,0.048644,0.803037,0.019489,40201.683551,9781.722494
5,FATR vanilla,0.000014,0.000036,0.400100,0.210607,0.000895,6.442443e-04,NaN,NaN,NaN,NaN,0.000000,0.000000,8109.904800,39.747839
6,FATR fair,0.000701,0.000118,0.000568,0.000166,0.000534,4.428914e-04,0.906025,0.115022,0.010154,0.032930,0.227912,0.021209,8109.904800,39.747839

In [7]:
df.drop(["time_mean","time_std"],axis=1, inplace=True)
df

,algorithm,tau_x_mean,tau_x_std,tau_y_mean,tau_y_std,ARI_true_labels_mean,ARI_true_labels_std,ARI_rows_mean,ARI_rows_std,ARI_cols_mean,ARI_cols_std,balance_bera_mean,balance_bera_std
0,Fast-$\tau$CC,0.005400,0.000011,0.005400,0.000011,0.000029,3.026243e-06,NaN,NaN,NaN,NaN,0.939764,0.012641
1,Fair-$\tau$CC v1,0.005390,0.000001,0.005390,0.000001,0.000027,5.939949e-07,0.925566,0.003572,0.938248,0.003281,0.950710,0.001407
2,Fair-$\tau$CC v2,0.005364,0.000046,0.005364,0.000046,0.000029,8.068858e-07,0.901993,0.006345,0.932204,0.010360,0.992909,0.000309
3,LBM,0.001955,0.000035,0.001967,0.000070,0.001561,1.840086e-04,NaN,NaN,NaN,NaN,0.393438,0.027894
4,Parity LBM,0.001896,0.000044,0.001908,0.000074,0.001297,8.136348e-05,0.347793,0.030571,0.768439,0.048644,0.803037,0.019489
5,FATR vanilla,0.000014,0.000036,0.400100,0.210607,0.000895,6.442443e-04,NaN,NaN,NaN,NaN,0.000000,0.000000
6,FATR fair,0.000701,0.000118,0.000568,0.000166,0.000534,4.428914e-04,0.906025,0.115022,0.010154,0.032930,0.227912,0.021209

In [8]:
csv_string = df.to_csv(index=False)
csv_string

'algorithm,tau_x_mean,tau_x_std,tau_y_mean,tau_y_std,ARI_true_labels_mean,ARI_true_labels_std,ARI_rows_mean,ARI_rows_std,ARI_cols_mean,ARI_cols_std,balance_bera_mean,balance_bera_std\nFast-$\tau$CC,0.0053998689864901,1.069906303788456e-05,0.0053998689864901,1.0699063037853612e-05,2.921702895001262e-05,3.026243205796141e-06,,,,,0.939764347081324,0.0126409598656377\nFair-$\tau$CC v1,0.0053902408664246,1.348203853718236e-06,0.0053902408664246,1.3482038536967045e-06,2.699118015523836e-05,5.93994894727116e-07,0.9255656340739818,0.0035724622725417,0.9382480689271184,0.0032812411770415,0.9507104344426908,0.0014071829771143\nFair-$\tau$CC v2,0.0053635265682578,4.555015951563467e-05,0.0053635265682579,4.555015951578305e-05,2.889033262440601e-05,8.068858475781347e-07,0.901993029561282,0.0063449972266477,0.932204320594492,0.0103603897899003,0.9929092856652584,0.0003088146550274\nLBM,0.0019548781128968,3.483291629184092e-05,0.0019668686788355,6.97470367371146e-05,0.0015614690300503,0.0001840086450128,,,,,0.393438011465871,0.027893869823605\nParity LBM,0.0018958996830931,4.371343340958689e-05,0.0019078442277187,7.355790363890704e-05,0.0012971090524846,8.136347660225874e-05,0.3477925329232694,0.0305709106650872,0.7684391816116499,0.0486437091855384,0.8030369272863801,0.019489430061258\nFATR vanilla,1.36901498510421e-05,3.5955771112066565e-05,0.4001002943565046,0.2106065341003591,0.0008952616521171,0.0006442442735349,,,,,0.0,0.0\nFATR fair,0.0007005387403647,0.0001179044095126,0.0005677557684685,0.0001663459514209,0.0005341449512446,0.0004428914147435,0.9060245550442,0.1150218946524476,0.010154125460695,0.0329295295069481,0.2279122210682,0.0212091478228528\n'

In [3]:
clusters = 3
groups = 2

df = pd.read_csv(root + f"/results/clus{clusters}_groups{groups}.csv")
df

,algorithm,tau_x_mean,tau_x_std,tau_y_mean,tau_y_std,ARI_rows_mean,ARI_rows_std,ARI_cols_mean,ARI_cols_std,ARI_van_rows_mean,ARI_van_rows_std,ARI_van_cols_mean,ARI_van_cols_std,balance_bera_mean,balance_bera_std,time_mean,time_std
0,taucc_vanilla,0.312614,0.016664,0.310931,0.018438,0.784965,0.226673,0.776239,0.236208,NaN,NaN,NaN,NaN,0.247284,0.260669,0.106322,0.050675
1,taucc_fair,0.033799,0.006284,0.187819,0.019036,0.156014,0.013932,0.865531,0.214638,0.087505,0.014777,0.478265,0.275858,1.000000,0.000000,27.482166,13.530435
2,taucc_fair_max,0.227913,0.005912,0.227913,0.005912,0.443365,0.000544,0.491602,0.049111,0.413583,0.064018,0.250696,0.291950,0.946575,0.001927,10.356761,4.527909